modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/Yuri-Almir-Pinto/kitchen-sink-inventory-mod/issues"
license = "MIT"

[[mods]]
modId = "unslotted"
version = "${version}"
displayName = "Unslotted"
authors = "Yipeekiyaay"
description = '''
Removes a considerable portion of your inventory slots, turning them into a space you can drag items around freeform instead.
'''
logoFile = "assets/unslotted/icon.png"

[[dependencies.unslotted]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.unslotted]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.unslotted]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "unslotted.mixins.json"
